add_library(rpc_compression STATIC src/compression.cpp)
add_library(lrpc::compression ALIAS rpc_compression)
target_include_directories(rpc_compression PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(rpc_compression PUBLIC lrpc::wire)
lrpc_configure_target(rpc_compression)
if(LRPC_ENABLE_COMPRESSION)
    find_package(zstd CONFIG REQUIRED)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(LZ4 REQUIRED IMPORTED_TARGET liblz4)
    target_link_libraries(rpc_compression PRIVATE zstd::libzstd_static PkgConfig::LZ4)
    target_compile_definitions(rpc_compression PRIVATE LRPC_HAS_COMPRESSION=1)
endif()
