add_executable(unary_echo unary_echo.cpp)
target_link_libraries(unary_echo PRIVATE lrpc::unary)
lrpc_configure_target(unary_echo)
if(LRPC_BUILD_TESTS)
    add_test(NAME unary_echo COMMAND unary_echo)
    set_tests_properties(unary_echo PROPERTIES TIMEOUT 10)
endif()

if(LRPC_BUILD_JSON)
    add_executable(json_users json_users.cpp)
    target_link_libraries(json_users PRIVATE lrpc::json)
    lrpc_configure_target(json_users)
    if(LRPC_BUILD_TESTS)
        add_test(NAME json_users COMMAND json_users)
        set_tests_properties(json_users PROPERTIES TIMEOUT 10)
    endif()
endif()

if(LRPC_BUILD_PROTOBUF AND LRPC_BUILD_CODEGEN)
    lrpc_generate_cpp(echo_protocol IMPORT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/proto" PROTOS echo.proto)
    add_executable(protobuf_echo protobuf_echo.cpp)
    target_link_libraries(protobuf_echo PRIVATE echo_protocol)
    lrpc_configure_target(protobuf_echo)
    if(LRPC_BUILD_TESTS)
        add_test(NAME protobuf_echo COMMAND protobuf_echo)
        set_tests_properties(protobuf_echo PROPERTIES TIMEOUT 10)
    endif()
endif()
