include_guard(GLOBAL)
# One provider, no configure-time download. RapidJSON's source target lacks a
# build-tree include interface, so explicitly supplied headers are wrapped here.
add_library(rpc_rapidjson INTERFACE)
add_library(lrpc::rapidjson ALIAS rpc_rapidjson)
set(LRPC_RAPIDJSON_SOURCE_DIR "" CACHE PATH "Path to an independent RapidJSON source checkout")
if(TARGET RapidJSON)
    target_link_libraries(rpc_rapidjson INTERFACE RapidJSON)
elseif(TARGET rapidjson)
    target_link_libraries(rpc_rapidjson INTERFACE rapidjson)
elseif(LRPC_RAPIDJSON_SOURCE_DIR)
    if(NOT EXISTS "${LRPC_RAPIDJSON_SOURCE_DIR}/include/rapidjson/reader.h")
        message(FATAL_ERROR "LRPC_RAPIDJSON_SOURCE_DIR must contain include/rapidjson/reader.h")
    endif()
    target_include_directories(rpc_rapidjson SYSTEM INTERFACE "${LRPC_RAPIDJSON_SOURCE_DIR}/include")
else()
    find_package(RapidJSON CONFIG REQUIRED)
    if(TARGET RapidJSON)
        target_link_libraries(rpc_rapidjson INTERFACE RapidJSON)
    elseif(TARGET rapidjson)
        target_link_libraries(rpc_rapidjson INTERFACE rapidjson)
    elseif(RAPIDJSON_INCLUDE_DIRS)
        target_include_directories(rpc_rapidjson SYSTEM INTERFACE "${RAPIDJSON_INCLUDE_DIRS}")
    else()
        message(FATAL_ERROR "RapidJSON provider has no target or include directories")
    endif()
endif()
